### ISSUE TITLE
login two times in the same browser

### ISSUE THREAD

**Issue by darrinholst** [hapijs/bell#433] opened 2019-09-21 15:37 UTC
Reopening of #209. I'm not sure if the OP had the same issue as me, but we're running into issues authenticating in the same browser (iframes in our case) and at, or nearly, the same time. The problem appears to be the use of a single cookie, `bell-custom`, for the same domain and the 2 different auth flows clobbering each other since there's only one cookie per domain per browser.

I have an example app here - https://github.com/dholst/bell-cookies.git - that exposes the problem. It loads 2 iframes pointing at the same endpoint which is authenticated by a local stubbed oauth 1.0 implementation.

Load the page and refresh a couple times and you'll see one or both error with either a `Error: Missing custom request token cookie` or a `Error: custom authorized request token mismatch` depending on the timing/sequence of the auth flow.

![7D0ADCEA-133C-4261-812A-184946937E56](https://user-images.githubusercontent.com/4854/65375442-800d4a00-dc5b-11e9-97fa-40dfc695fea6.png)

![400CF515-82F9-41E9-9600-A56E711CA7D0](https://user-images.githubusercontent.com/4854/65375445-84d1fe00-dc5b-11e9-92ae-8e19b7d5d4e8.png)

**Comment by hueniverse** [comment] 2019-09-21 17:06
Thanks for the details. Yep, bell was not designed to support more than one flow at a time. To make this work, we'll need to add some dynamic suffix to the cookie name and use the state parameter to indicate which cookie to use upon return. The problem is that there is no clean way to separate the security zones of these two sessions and one could steal the other. I also not sure about other potential attack vectors coming out of the state parameter containing internal implementation detail (unless we iron it).

Then of course is the other problem of what to do once you have two authenticated sessions with different credentials. How do you sort that part out? You will need the same kind of support on your session cookie.

I'm inclined not to support this use case mostly because it is not covered by existing well-established patterns. I don't recall this ever coming up in my 5 years working on OAuth 1 and 2.

Assuming you are using the same third-party provider and account on both iframes (if not, it's a really bad idea to mix credentials/providers in the same browser sandbox), I would suggest either moving to client-side login flow and then passing the access token back to hapi once everything is done client side (normal OAuth browser flow), or finding a way to sync the two iframes in your app code, and one waiting on the other to finish.

If humans are involved, they can't really perform two auth flows at the same time unless they start, pause, switch, etc. which is unsupported by any site I've seen.

Closing but please feel free to continue the conversation.

**Closed by hueniverse** 2019-09-21 17:06 UTC
Labels: feature

**Comment by darrinholst** [comment] 2019-09-21 18:24
Yeah, I get it. 

>  I don't recall this ever coming up in my 5 years working on OAuth 1 and 2.

pretty sure that's what the OP of #209 was dealing with, but I agree it's super rare and we do have security concerns when changing this stuff up

> Then of course is the other problem of what to do once you have two authenticated sessions with different credentials.

Same user/credentials, just 2 different "components" hitting the same 3rd party api.

> If humans are involved,

They are, it's just that I'm already authenticated at the 3rd party so there's no explicit consent step. It's just a matter of going through all 3 legs and getting new tokens.

fwiw and for anyone else in the future that runs into this [here](https://github.com/dholst/bell-cookies/commit/0807b7e75d808a5ef9a6c1f708e04a4c0a5dd95e#diff-168726dbe96b3ce427e7fedce31bb0bcR106-R117) is how I plan on handling it. Seems to work in the demo app. tl;dr intercept the 3rd leg and if there's no cookie or the tokens don't match then wait a bit and redirect them back through the login process.

![37ABCEFC-18E7-4B52-9797-83848D75FD99](https://user-images.githubusercontent.com/4854/65377522-dcc82f00-dc72-11e9-9f7d-7f325ef464bc.png)

**Comment by hueniverse** [comment] 2019-09-21 21:08
Clever.
